var songs = [
  {
    name: 'Cherry Blossom', sub: 'ENERGETIC', bpm: 152, color: '#ff69b4',
    bg1: '#1a0010', bg2: '#300025', bars: 70, cover: 'Music/Cherry Blossom/cherry blossom.png',
    file: 'Music/Cherry_Blossom_Sprint.ogg',
    stemDir: 'Music/Cherry Blossom/',
    stemPrefix: 'cherry blossom',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 109.2,
    pattern: [1,0,1,0,1,0,1,1, 0,1,0,1,1,0,1,0],
  },
  {
    name: 'Insert Coin Go Hard', sub: 'ARCADE', bpm: 140, color: '#00e5ff',
    bg1: '#000520', bg2: '#001040', bars: 91, cover: 'Music/Insert_Coin_Go_Hard/Insert_Coin_Go_Hard.png',
    file: 'Music/Insert_Coin_Go_Hard.ogg',
    stemDir: 'Music/Insert_Coin_Go_Hard/',
    stemPrefix: 'insert_coin_go_hard',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 153.7,
    pattern: [1,0,1,1,0,1,0,1, 1,0,0,1,1,0,1,0],
  },
  {
    name: 'CLIMB TO THE CROWN', sub: 'ROCK/ELECTRO', bpm: 160, color: '#ff2200',
    bg1: '#1a0500', bg2: '#350a00', bars: 72, cover: 'Music/CLIMB_TO_THE_CROWN/CLIMB_TO_THE_CROWN.png',
    file: 'Music/CLIMB_TO_THE_CROWN.ogg',
    stemDir: 'Music/CLIMB_TO_THE_CROWN/',
    stemPrefix: 'CLIMB_TO_THE_CROWN',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 106.7,
    pattern: [1,0,1,1,1,0,1,0, 1,1,0,1,0,1,1,0],
  },
  {
    name: '어깨 위에 내려앉은 봄', sub: 'BALLAD', bpm: 89, color: '#ffb7d5',
    bg1: '#0f0808', bg2: '#1e1215', bars: 66, cover: 'Music/어깨_위에_내려앉은_봄/어깨_위에_내려앉은_봄.png',
    file: 'Music/어깨_위에_내려앉은_봄.ogg',
    stemDir: 'Music/어깨_위에_내려앉은_봄/',
    stemPrefix: '어깨_위에_내려앉은_봄',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 175.7,
    pattern: [1,0,0,1,0,0,1,0, 0,1,0,0,1,0,0,1],
  },
  {
    name: '차선 사이의 침묵', sub: 'DARK AMBIENT', bpm: 110, color: '#6677aa',
    bg1: '#050810', bg2: '#0a1020', bars: 40, cover: 'Music/차선_사이의_침묵/차선_사이의_침묵.png',
    file: 'Music/차선_사이의_침묵.ogg',
    stemDir: 'Music/차선_사이의_침묵/',
    stemPrefix: '차선_사이의_침묵',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,0,1,0,1,0,0, 1,0,1,0,0,1,0,0],
  },
  {
    name: '止まれない鼓動', sub: 'J-ROCK', bpm: 155, color: '#e63946',
    bg1: '#120008', bg2: '#250010', bars: 83, cover: 'Music/止まれない鼓動/止まれない鼓動.png',
    file: 'Music/止まれない鼓動.ogg',
    stemDir: 'Music/止まれない鼓動/',
    stemPrefix: '止まれない鼓動',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,1,0,1,1,0,1, 0,1,1,0,1,0,1,0],
  },
  {
    name: '境界線を蹴り飛ばして', sub: 'J-PUNK', bpm: 170, color: '#ff6a00',
    bg1: '#1a0800', bg2: '#301500', bars: 83, cover: 'Music/境界線を蹴り飛ばして/境界線を蹴り飛ばして.png',
    file: 'Music/境界線を蹴り飛ばして.ogg',
    stemDir: 'Music/境界線を蹴り飛ばして/',
    stemPrefix: '境界線を蹴り飛ばして',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 115.2,
    pattern: [1,1,0,1,0,1,1,0, 1,0,1,0,1,1,0,1],
  },
  {
    name: 'The Clock Face Shakes', sub: 'SYNTH/ELECTRONIC', bpm: 135, color: '#7b2ff7',
    bg1: '#0a0020', bg2: '#150040', bars: 67, cover: 'Music/The_Clock_Face_Shakes/The_Clock_Face_Shakes.png',
    file: 'Music/The_Clock_Face_Shakes.ogg',
    stemDir: 'Music/The_Clock_Face_Shakes/',
    stemPrefix: 'The_Clock_Face_Shakes',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 117.2,
    pattern: [1,0,1,0,1,0,1,0, 1,0,1,0,1,0,1,0],
  },
  {
    name: 'Breaking Gravity', sub: 'EDM/BASS', bpm: 145, color: '#00e0ff',
    bg1: '#000a14', bg2: '#001428', bars: 63, cover: 'Music/Breaking_Gravity/Breaking_Gravity.png',
    file: 'Music/Breaking_Gravity.ogg',
    stemDir: 'Music/Breaking_Gravity/',
    stemPrefix: 'Breaking_Gravity',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 102.2,
    pattern: [1,0,1,1,0,1,0,1, 1,0,1,0,1,1,0,1],
  },
  {
    name: '손 끝 아래', sub: 'K-EMOTION', bpm: 120, color: '#e8a0c0',
    bg1: '#0c0515', bg2: '#1a0a25', bars: 57, cover: 'Music/손_끝_아래/손_끝_아래.png',
    file: 'Music/손_끝_아래.ogg',
    stemDir: 'Music/손_끝_아래/',
    stemPrefix: '손_끝_아래',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 112.2,
    pattern: [1,0,0,1,0,1,0,1, 0,0,1,0,1,0,0,1],
  },
  {
    name: '멈춘 시계', sub: 'K-AMBIENT', bpm: 123, color: '#8ba4b8',
    bg1: '#060a10', bg2: '#0e1520', bars: 73, cover: 'Music/멈춘_시계/멈춘_시계.png',
    file: 'Music/멈춘_시계.ogg',
    stemDir: 'Music/멈춘_시계/',
    stemPrefix: '멈춘_시계',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 140.2,
    pattern: [1,0,1,0,1,0,1,0, 0,1,0,1,0,1,0,1],
  },
  {
    name: 'SIDEWALK RUNWAY', sub: 'POP/HIPHOP', bpm: 117, color: '#e040fb',
    bg1: '#12041a', bg2: '#220a30', bars: 52, cover: 'Music/SIDEWALK_RUNWAY/SIDEWALK_RUNWAY.png',
    file: 'Music/Sidewalk_Runway.ogg',
    stemDir: 'Music/SIDEWALK_RUNWAY/',
    stemPrefix: 'SIDEWALK_RUNWAY',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 96.2,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,1,0,1,0],
  },
  {
    name: "Let's Go Shopping!", sub: 'POP/DANCE', bpm: 130, color: '#ff7eb3',
    bg1: '#1a0818', bg2: '#2d1028', bars: 45, cover: "Music/Let's_Go_Shopping!/Let's_Go_Shopping!.png",
    file: "Music/Let's_Go_Shopping!.ogg",
    stemDir: "Music/Let's_Go_Shopping!/",
    stemPrefix: "Let's_Go_Shopping!",
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 77.2,
    pattern: [1,0,1,1,0,1,0,1, 1,0,1,0,1,1,0,1],
  },
  {
    name: 'Glitch Heartbeat', sub: 'GLITCH/ELECTRO', bpm: 138, color: '#00ffc8',
    bg1: '#000d0a', bg2: '#001a14', bars: 63,
    cover: 'Music/Glitch_Heartbeat/Glitch_Heartbeat.png',
    file: 'Music/Glitch_Heartbeat.ogg',
    stemDir: 'Music/Glitch_Heartbeat/',
    stemPrefix: 'Glitch_Heartbeat',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 107.3,
    pattern: [1,0,1,0,1,1,0,1, 0,1,1,0,1,0,1,0],
  },
  {
    name: 'Midnight Boulevard', sub: 'CHILL/LOFI', bpm: 96, color: '#5566cc',
    bg1: '#05051a', bg2: '#0a0a30', bars: 43,
    cover: 'Music/Midnight_Boulevard/Midnight_Boulevard.png',
    file: 'Music/Midnight_Boulevard.ogg',
    stemDir: 'Music/Midnight_Boulevard/',
    stemPrefix: 'Midnight_Boulevard',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 106.2,
    pattern: [1,0,0,1,0,0,1,0, 0,1,0,0,1,0,0,1],
  },
  {
    name: 'Outrunning The Rain', sub: 'INDIE/POP', bpm: 128, color: '#4488cc',
    bg1: '#060e18', bg2: '#0c1c30', bars: 46,
    cover: 'Music/Outrunning_The_Rain/Outrunning_The_Rain.png',
    file: 'Music/Outrunning_The_Rain.ogg',
    stemDir: 'Music/Outrunning_The_Rain/',
    stemPrefix: 'Outrunning_The_Rain',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 84.7,
    pattern: [1,0,1,0,1,0,1,1, 0,1,0,1,0,1,1,0],
  },
  {
    name: 'Ten Thousand Taps', sub: 'SPEEDCORE', bpm: 175, color: '#ff3355',
    bg1: '#1a0005', bg2: '#33000a', bars: 82,
    cover: 'Music/Ten_Thousand_Taps/Ten_Thousand_Taps.png',
    file: 'Music/Ten_Thousand_Taps.ogg',
    stemDir: 'Music/Ten_Thousand_Taps/',
    stemPrefix: 'Ten_Thousand_Taps',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 110.2,
    pattern: [1,1,0,1,1,0,1,1, 0,1,1,0,1,1,0,1],
  },
  {
    name: 'The Final Sprint', sub: 'EPIC/CINEMATIC', bpm: 148, color: '#ffaa00',
    bg1: '#0f0800', bg2: '#1e1000', bars: 66,
    cover: 'Music/The_Final_Sprint/The_Final_Sprint.png',
    file: 'Music/The_Final_Sprint.ogg',
    stemDir: 'Music/The_Final_Sprint/',
    stemPrefix: 'The_Final_Sprint',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 105.7,
    pattern: [1,0,1,0,1,1,0,1, 1,0,1,1,0,1,0,1],
  },
  {
    name: '힙합 오소리', sub: 'K-HIPHOP', bpm: 100, color: '#88cc44',
    bg1: '#080e04', bg2: '#101c08', bars: 38,
    cover: 'Music/힙합_오소리/힙합_오소리.png',
    file: 'Music/힙합_오소리.ogg',
    stemDir: 'Music/힙합_오소리/',
    stemPrefix: '힙합_오소리',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,1,0,1,1,0,1, 1,0,1,1,0,1,0,1],
  },
  {
    name: 'Heart On The Line', sub: 'POP/BALLAD', bpm: 117, color: '#ff6699',
    bg1: '#0e0408', bg2: '#1c0810', bars: 53,
    cover: 'Music/Heart_On_The_Line/Heart_On_The_Line.png',
    file: 'Music/Heart_On_The_Line.ogg',
    stemDir: 'Music/Heart_On_The_Line/',
    stemPrefix: 'Heart_on_the_Line',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 105.7,
    pattern: [1,0,1,0,1,0,1,0, 1,0,1,1,0,1,0,1],
  },
  {
    name: '기억의 사물함', sub: 'K-BALLAD', bpm: 80, color: '#9999dd',
    bg1: '#060610', bg2: '#0c0c1c', bars: 37,
    cover: 'Music/기억의_사물함/기억의_사물함.png',
    file: 'Music/기억의_사물함.ogg',
    stemDir: 'Music/기억의_사물함/',
    stemPrefix: '기억의_사물함',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 104.7,
    pattern: [1,0,0,1,1,0,0,1, 1,0,0,1,1,0,0,1],
    excludeStems: [0, 1, 5, 6], // drums/bass/guitar/other 제외 → instrum + piano만
  },
  {
    name: 'Black Out', sub: 'DARK/CLUB', bpm: 161, color: '#aa44ff',
    bg1: '#0a0015', bg2: '#180025', bars: 81,
    cover: 'Music/Black_Out/Black_Out.png',
    file: 'Music/Black_Out.ogg',
    stemDir: 'Music/Black_Out/',
    stemPrefix: 'Black_Out',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 113.7,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,1,0,1,0],
  },
  {
    name: 'Burn It All Down', sub: 'HARD ROCK', bpm: 152, color: '#ff4400',
    bg1: '#180400', bg2: '#300a00', bars: 75,
    cover: 'Music/Burn_It_All_Down/Burn_It_All_Down.png',
    file: 'Music/Burn_It_All_Down.ogg',
    stemDir: 'Music/Burn_It_All_Down/',
    stemPrefix: 'Burn_It_All_Down',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 114.7,
    pattern: [1,1,0,1,1,0,1,1, 0,1,1,0,1,1,0,1],
  },
  {
    name: 'No More Scripts', sub: 'TRAP/HIPHOP', bpm: 129, color: '#ffcc00',
    bg1: '#120e00', bg2: '#241c00', bars: 64,
    cover: 'Music/No_More_Scripts/No_More_Scripts.png',
    file: 'Music/No_More_Scripts.ogg',
    stemDir: 'Music/No_More_Scripts/',
    stemPrefix: 'No_More_Scripts',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 107.2,
    pattern: [1,0,0,1,0,1,0,0, 1,0,1,0,0,1,0,1],
    // 'auto': 런타임에 스템 RMS 분석으로 보컬-only 구간 자동 감지 (인트로 + 중간 보컬 브레이크 전부)
    vocalIntroRange: 'auto',
  },
  {
    name: 'Polaroid In Bloom', sub: 'DREAM POP', bpm: 108, color: '#ffb3e0',
    bg1: '#160812', bg2: '#281425', bars: 66,
    cover: 'Music/Polaroid_In_Bloom/Polaroid_In_Bloom.png',
    file: 'Music/Polaroid_In_Bloom.ogg',
    stemDir: 'Music/Polaroid_In_Bloom/',
    stemPrefix: 'Polaroid_In_Bloom',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 136.7,
    pattern: [1,0,1,0,0,1,0,1, 1,0,0,1,0,1,0,1],
  },
  {
    name: 'RED TAPE', sub: 'INDUSTRIAL', bpm: 89, color: '#ff1a33',
    bg1: '#180003', bg2: '#30000a', bars: 59,
    cover: 'Music/RED_TAPE/RED_TAPE.png',
    file: 'Music/RED_TAPE.ogg',
    stemDir: 'Music/RED_TAPE/',
    stemPrefix: 'RED_TAPE',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 157.2,
    pattern: [1,0,1,1,0,1,0,1, 1,1,0,1,0,1,1,0],
    // piano RMS 0.0000 인데 onset 425 / other RMS 0.015 에 onset 310 — noise floor 허위 트리거.
    excludeStems: [4, 6],
    // intro 0~10초: auto onset 모두 drop.
    introSparse: [0, 10, 100],
    // 딱! 시점 4개 (오디오 분석).
    introTaps: [1.44, 4.11, 6.76, 9.43],
    // 딱! 사이 조용한 구간 4곳에 hold. 각 hold 끝 ↔ 다음 tap 사이 0.3s+ 마진 (동일레인 tap 삭제 방지).
    // 지옥 난이도는 각 hold 가 반반 쪼개져 연달아 hold 2개로 (총 8 hold).
    introHolds: [
      [0.3, 0.8],   // 0.3 ~ 1.1  (첫 딱! 1.44 전, 마진 0.34s)
      [2.0, 1.6],   // 2.0 ~ 3.6  (1.44 ~ 4.11 사이, 마진 0.51s)
      [4.6, 1.7],   // 4.6 ~ 6.3  (4.11 ~ 6.76 사이, 마진 0.46s)
      [7.2, 1.7],   // 7.2 ~ 8.9  (6.76 ~ 9.43 사이, 마진 0.53s)
    ],
  },
  {
    name: '加速する鼓動', sub: 'J-ROCK/SPEED', bpm: 172, color: '#ff3377',
    bg1: '#150008', bg2: '#2a0010', bars: 83,
    cover: 'Music/加速する鼓動/加速する鼓動.png',
    file: 'Music/加速する鼓動.ogg',
    stemDir: 'Music/加速する鼓動/',
    stemPrefix: '加速する鼓動',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 112.7,
    pattern: [1,1,0,1,1,0,1,0, 1,0,1,1,0,1,1,0],
  },
  {
    name: '황덕구의 모험', sub: 'K-FUNK/FUN', bpm: 117, color: '#ffdd33',
    bg1: '#141000', bg2: '#281e00', bars: 71,
    cover: 'Music/황덕구의_모험/황덕구의_모험.png',
    file: 'Music/황덕구의_모험.ogg',
    stemDir: 'Music/황덕구의_모험/',
    stemPrefix: '황덕구의_모험',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 142.2,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,1,0,1,0],
    excludeStems: [0, 1, 4, 5, 6], // instrum만 사용 (메인 트랙)
  },
  {
    name: 'Catch The Sky', sub: 'POP/UPLIFT', bpm: 120, color: '#66d4ff',
    bg1: '#0a1828', bg2: '#163450', bars: 60,
    cover: 'Music/Catch_The_Sky/Catch_The_Sky.png',
    file: 'Music/Catch_The_Sky.ogg',
    stemDir: 'Music/Catch_The_Sky/',
    stemPrefix: 'Catch_The_Sky',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 116.75,
    pattern: [1,0,1,0,1,0,1,1, 0,1,0,1,1,0,1,0],
  },
  {
    name: 'Neon Light', sub: 'SYNTH/NIGHT', bpm: 110, color: '#ff5cd6',
    bg1: '#1a0820', bg2: '#33103d', bars: 54,
    cover: 'Music/Neon_Light/Neon_Light.png',
    file: 'Music/Neon_Light.ogg',
    stemDir: 'Music/Neon_Light/',
    stemPrefix: 'Neon_Light',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 109.2,
    pattern: [1,1,0,1,1,0,1,0, 1,0,1,1,0,1,1,0],
    excludeStems: [4, 5], // piano, guitar 빈 스템
  },
  {
    name: 'Vincere Aut Mori', sub: 'EPIC/BATTLE', bpm: 120, color: '#ff3344',
    bg1: '#1c0608', bg2: '#3a0c10', bars: 59,
    cover: 'Music/Vincere_Aut_Mori/Vincere_Aut_Mori.png',
    file: 'Music/Vincere_aut_mori.ogg',
    stemDir: 'Music/Vincere_Aut_Mori/',
    stemPrefix: 'Vincere_Aut_Mori',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 115.7,
    pattern: [1,0,1,1,0,1,0,1, 1,0,1,0,1,1,0,1],
    excludeStems: [1, 4], // bass, piano 빈 스템
  },
  {
    name: "Let's Go Shopping!", sub: 'Bright Pop', bpm: 152,
    color: '#ff6699', bg1: '#4a0028', bg2: '#1a0a1a',
    bars: 52, file: "Music/Let's_Go_Shopping!.ogg",
    cover: "Music/Let's_Go_Shopping!/Let's_Go_Shopping!.png",
    stemDir: "Music/Let's_Go_Shopping!/",
    stemPrefix: "Let's_Go_Shopping!",
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 77.2,
    pattern: [1,0,1,0,1,0,1,0, 1,1,0,1,0,1,0,1],
    excludeStems: [4, 5], chordMode: true,
  },
  {
    name: 'Midnight Breeze', sub: 'Chill R&B', bpm: 117,
    color: '#6688cc', bg1: '#0a1428', bg2: '#020810',
    bars: 57, file: 'Music/Midnight_Breeze.ogg',
    cover: 'Music/Midnight_Breeze/Midnight_Breeze.png',
    stemDir: 'Music/Midnight_Breeze/',
    stemPrefix: 'Midnight_Breeze',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 114.2,
    pattern: [1,0,0,1,0,0,1,0, 0,1,0,0,1,0,0,1],
    excludeStems: [4, 5], chordMode: true,
  },
  {
    name: 'Pebbles To Granite', sub: 'Hip-Hop', bpm: 89,
    color: '#aa8855', bg1: '#2a1a08', bg2: '#0a0804',
    bars: 44, file: 'Music/Pebbles_To_Granite.ogg',
    cover: 'Music/Pebbles_To_Granite/Pebbles_To_Granite.png',
    stemDir: 'Music/Pebbles_To_Granite/',
    stemPrefix: 'Pebbles_To_Granite',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 116.5,
    pattern: [1,0,0,1,0,1,0,0, 1,0,0,1,0,0,1,0],
    excludeStems: [5], chordMode: true,
  },
  {
    name: 'Rainbow Flight', sub: 'Synth Pop', bpm: 117,
    color: '#ff77aa', bg1: '#28082a', bg2: '#0a0416',
    bars: 54, file: 'Music/Rainbow_Flight.ogg',
    cover: 'Music/Rainbow_Flight/Rainbow_Flight.png',
    stemDir: 'Music/Rainbow_Flight/',
    stemPrefix: 'Rainbow_Flight',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
    excludeStems: [4, 5], chordMode: true,
  },
  {
    name: 'Velocity And Pride', sub: 'EDM / Anthem', bpm: 152,
    color: '#ff4444', bg1: '#2a0808', bg2: '#100404',
    bars: 95, file: 'Music/Velocity_And_Pride.ogg',
    cover: 'Music/Velocity_And_Pride/Velocity and Pride.png',
    stemDir: 'Music/Velocity_And_Pride/',
    stemPrefix: 'Velocity_And_Pride',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 146.2,
    pattern: [1,0,1,1,0,1,0,1, 1,0,1,0,1,1,0,1],
    excludeStems: [4, 5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '靴紐を結び直して', sub: 'J-Pop', bpm: 117,
    color: '#55ccaa', bg1: '#082a1a', bg2: '#041008',
    bars: 58, file: 'Music/靴紐を結び直して.ogg',
    cover: 'Music/靴紐を結び直して/靴紐を結び直して.png',
    stemDir: 'Music/靴紐を結び直して/',
    stemPrefix: '靴紐を結び直して',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 116.2,
    pattern: [1,0,1,0,0,1,0,1, 0,1,0,1,0,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '기분 좋은 날', sub: 'K-Pop Ballad', bpm: 92,
    color: '#ffcc44', bg1: '#2a2008', bg2: '#100c04',
    bars: 51, file: 'Music/기분_좋은_날.ogg',
    cover: 'Music/기분_좋은_날/기분_좋은_날.png',
    stemDir: 'Music/기분_좋은_날/',
    stemPrefix: '기분_좋은_날',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 130.2,
    pattern: [1,0,0,1,0,0,1,0, 0,1,0,0,1,0,0,1],
    excludeStems: [5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '바람을 타고', sub: 'K-Pop Dance', bpm: 172,
    color: '#44bbff', bg1: '#081a2a', bg2: '#040a10',
    bars: 117, file: 'Music/바람을_타고.ogg',
    cover: 'Music/바람을_타고/바람을_타고.png',
    stemDir: 'Music/바람을_타고/',
    stemPrefix: '바람을_타고',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 157.2,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,1,0,1,0],
    excludeStems: [5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'The Last Quarter', sub: 'Alt Rock', bpm: 144,
    color: '#88aadd', bg1: '#0a1828', bg2: '#040810',
    bars: 71, file: 'Music/The_Last_Quarter.ogg',
    cover: 'Music/The_Last_Quarter/The_Last_Quarter.png',
    stemDir: 'Music/The_Last_Quarter/',
    stemPrefix: 'The_Last_Quarter',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,1,0,1,1,0,1, 1,0,1,0,1,0,1,1],
    excludeStems: [4, 5], chordMode: true,
  },
  {
    name: '밤하늘의 기적', sub: 'Midtempo Ballad', bpm: 123,
    color: '#9966ff', bg1: '#1a0a2c', bg2: '#0a0414',
    bars: 76, file: 'Music/밤하늘의_기적.ogg',
    cover: 'Music/밤하늘의_기적/밤하늘의_기적.png',
    stemDir: 'Music/밤하늘의_기적/',
    stemPrefix: '밤하늘의_기적',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 143.2,
    pattern: [1,0,0,1,1,0,1,0, 1,0,0,1,0,1,1,0],
    excludeStems: [4, 5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '별빛 아래의 약속', sub: 'Acoustic Ballad', bpm: 96,
    color: '#c8a2f0', bg1: '#1a1030', bg2: '#080416',
    bars: 69, file: 'Music/별빛_아래의_약속.ogg',
    cover: 'Music/별빛_아래의_약속/별빛_아래의_약속.png',
    stemDir: 'Music/별빛_아래의_약속/',
    stemPrefix: '별빛_아래의_약속',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 168.7,
    pattern: [1,0,0,1,0,1,0,0, 1,0,0,1,0,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '질주', sub: 'Indie Rock', bpm: 92,
    color: '#ff6b44', bg1: '#2c0e08', bg2: '#140804',
    bars: 57, file: 'Music/질주.ogg',
    cover: 'Music/질주/질주.png',
    stemDir: 'Music/질주/',
    stemPrefix: '질주',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 144.2,
    pattern: [1,0,0,0,1,0,1,0, 1,0,0,1,0,1,0,1],
    excludeStems: [4, 6], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'Higher', sub: 'UPLIFT POP', bpm: 96,
    color: '#6ab4ff', bg1: '#021530', bg2: '#042a50',
    bars: 53, file: 'Music/Higher.ogg',
    cover: 'Music/Higher/Higher.png',
    stemDir: 'Music/Higher/',
    stemPrefix: 'Higher',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 130.7,
    pattern: [1,0,1,0,1,1,0,1, 1,0,1,0,1,0,1,1],
    excludeStems: [4, 6], chordMode: true,
  },
  {
    name: 'Monoliths of Light', sub: 'AMBIENT', bpm: 60,
    color: '#b0d8ff', bg1: '#0a1a30', bg2: '#152544',
    bars: 29, file: 'Music/Monoliths_of_Light.ogg',
    cover: 'Music/Monoliths_of_Light/Monoliths_of_Light.png',
    stemDir: 'Music/Monoliths_of_Light/',
    stemPrefix: 'Monoliths_of_Light',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 111.2,
    pattern: [1,0,0,0,1,0,0,1, 1,0,0,1,0,0,1,0],
    excludeStems: [4, 5], vocalIntroRange: 'auto', chordMode: true,
    // 저BPM + ambient + excludeStems 많음 → noteSparse 회귀. slotSubdivision 0.5 + levelBonus.
    stemSensitivity: { 2: 0.9, 3: 0.9, 6: 0.95 },
    stemMinGap: { 2: 20, 3: 20 },
    slotSubdivision: 0.5,
    levelBonus: 0.3,
  },
  {
    name: 'Poolside Punch', sub: 'SUMMER POP', bpm: 123,
    color: '#ff8c55', bg1: '#201005', bg2: '#3a1a0a',
    bars: 60, file: 'Music/Poolside_Punch.ogg',
    cover: 'Music/Poolside_Punch/Poolside_Punch.png',
    stemDir: 'Music/Poolside_Punch/',
    stemPrefix: 'Poolside_Punch',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 114.7,
    pattern: [1,0,1,0,1,0,1,1, 0,1,0,1,1,0,1,0],
    excludeStems: [5],
    chordMode: true,
  },
  {
    name: 'PUNCH', sub: 'DRIVE/ROCK', bpm: 144,
    color: '#ff3333', bg1: '#280000', bg2: '#400400',
    bars: 75, file: 'Music/PUNCH.ogg',
    cover: 'Music/PUNCH/PUNCH.png',
    stemDir: 'Music/PUNCH/',
    stemPrefix: 'PUNCH',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 122.2,
    pattern: [1,1,0,1,1,0,1,1, 0,1,1,0,1,1,0,1],
    // other stem: 106s 에서 소리 끝나는데 onset 은 122s 까지 잡힘 (phantom) → 제외
    excludeStems: [4, 6], chordMode: true,
  },
  {
    name: 'Soda Pop Crush', sub: 'BUBBLY POP', bpm: 112,
    color: '#ff80b8', bg1: '#220a1c', bg2: '#3a1530',
    bars: 79, file: 'Music/Soda_Pop_Crush.ogg',
    cover: 'Music/Soda_Pop_Crush/Soda_Pop_Crush.png',
    stemDir: 'Music/Soda_Pop_Crush/',
    stemPrefix: 'Soda_Pop_Crush',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 167.2,
    pattern: [1,0,1,0,1,0,0,1, 1,1,0,1,0,1,0,1],
    excludeStems: [4],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'T', sub: 'POP/DANCE', bpm: 129,
    color: '#a0ff80', bg1: '#0a2008', bg2: '#143814',
    bars: 86, file: 'Music/T.ogg',
    cover: 'Music/T/T.png',
    stemDir: 'Music/T/',
    stemPrefix: 'T',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 157.7,
    pattern: [1,0,1,1,0,1,0,1, 1,0,0,1,1,0,1,0],
    excludeStems: [4, 5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'さいごまではしる', sub: 'J-ROCK', bpm: 136,
    color: '#ff9455', bg1: '#2a1005', bg2: '#44200a',
    bars: 97, file: 'Music/さいごまではしる.ogg',
    cover: 'Music/さいごまではしる/さいごまではしる.png',
    stemDir: 'Music/さいごまではしる/',
    stemPrefix: 'さいごまではしる',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,1,1,1,0,1,1, 0,1,1,0,1,1,0,1],
    excludeStems: [4, 6], chordMode: true,
  },
  {
    name: '날개를 펼쳐', sub: 'K-POP BALLAD', bpm: 96,
    color: '#ffb0d0', bg1: '#1a0a1a', bg2: '#2a1430',
    bars: 66, file: 'Music/날개를_펼쳐.ogg',
    cover: 'Music/날개를_펼쳐/날개를_펼쳐.png',
    stemDir: 'Music/날개를_펼쳐/',
    stemPrefix: '날개를_펼쳐',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 163.7,
    pattern: [1,0,0,1,1,0,0,1, 0,1,0,0,1,0,1,0],
    excludeStems: [4, 5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '달의 파편', sub: 'K-POP', bpm: 136,
    color: '#b888ff', bg1: '#100520', bg2: '#201040',
    bars: 89, file: 'Music/달의_파편.ogg',
    cover: 'Music/달의_파편/달의_파편.png',
    stemDir: 'Music/달의_파편/',
    stemPrefix: '달의_파편',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 153.7,
    pattern: [1,0,1,0,1,1,0,1, 0,1,1,0,1,0,1,1],
    excludeStems: [5],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '토끼의 꿈', sub: 'DREAM POP', bpm: 129,
    color: '#ffd0e8', bg1: '#18081a', bg2: '#2c1030',
    bars: 84, file: 'Music/토끼의_꿈.ogg',
    cover: 'Music/토끼의_꿈/토끼의_꿈.png',
    stemDir: 'Music/토끼의_꿈/',
    stemPrefix: '토끼의_꿈',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,0,1,1,0,1,0, 1,0,1,0,0,1,1,0],
    excludeStems: [4, 5], vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '투명한 설렘', sub: 'CLEAR BALLAD', bpm: 89,
    color: '#a0e0ff', bg1: '#0a1a26', bg2: '#14303c',
    bars: 55, file: 'Music/투명한_설렘.ogg',
    cover: 'Music/투명한_설렘/투명한_설렘.png',
    stemDir: 'Music/투명한_설렘/',
    stemPrefix: '투명한_설렘',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 145.2,
    pattern: [1,0,0,1,0,0,1,0, 1,0,0,1,0,1,0,1],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '고민의 자국', sub: 'HEARTFELT BALLAD', bpm: 99,
    color: '#c98ad6', bg1: '#1a0d22', bg2: '#2e1338',
    bars: 51, file: 'Music/고민의_자국.ogg',
    cover: 'Music/고민의_자국/고민의_자국.png',
    stemDir: 'Music/고민의_자국/',
    stemPrefix: '고민의_자국',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4],
    endCutoff: 121.7,
    pattern: [1,0,1,0,0,1,0,1, 1,0,0,1,0,1,1,0],
    chordMode: true,
  },
  {
    name: '괜찮아', sub: 'WARM POP', bpm: 136,
    color: '#ffb380', bg1: '#1f0e08', bg2: '#3a1a10',
    bars: 125, file: 'Music/괜찮아.ogg',
    cover: 'Music/괜찮아/괜찮아.png',
    stemDir: 'Music/괜찮아/',
    stemPrefix: '괜찮아',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 218.2,
    pattern: [1,0,1,0,1,0,1,0, 1,0,0,1,0,1,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'Fragment', sub: 'INDIE / ALT', bpm: 92,
    color: '#6b88ff', bg1: '#0a0f1f', bg2: '#14182d',
    bars: 56, file: 'Music/Fragment.ogg',
    cover: 'Music/Fragment/Fragment.png',
    stemDir: 'Music/Fragment/',
    stemPrefix: 'Fragment',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4],
    endCutoff: 140.7,
    pattern: [1,0,0,1,0,1,0,0, 1,0,1,0,0,1,0,1],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'Lucifer', sub: 'ROCK / METAL', bpm: 161,
    color: '#d4264c', bg1: '#1a0006', bg2: '#2e000d',
    bars: 111, file: 'Music/Lucifer.ogg',
    cover: 'Music/Lucifer/Lucifer.png',
    stemDir: 'Music/Lucifer/',
    stemPrefix: 'Lucifer',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 164.0,
    pattern: [1,1,0,1,0,1,1,0, 1,0,1,1,0,1,0,1],
    chordMode: true,
    // piano 만 lenient (1.05) + decay 60ms 차단. 다른 stem 기본 1.1.
    // slotStemPriority piano 우선 (분리).
    stemSensitivity: { 4: 1.05 },
    stemMinGap: { 4: 60 },
    slotSubdivision: 0.75, // 어려움: 점8분 × 0.75 = 105ms@161BPM
    hellSubdivision: 1.2,  // 지옥 only — sixteenth × 1.2 × 0.75 = 85ms (어려움보다 살짝 dense, 70ms 보다 sparse)
    slotStemPriority: [4, 5, 3, 0, 1, 6, 2], // piano > guitar > 신스 > drum > bass > other > vocal
    // slotStemPriority 제거: 순수 energy 기반 picker (가장 쎈 음만)
  },
  {
    name: 'Spin', sub: 'JAZZ / SLOW', bpm: 78,
    color: '#f4c542', bg1: '#1f1808', bg2: '#2e2410',
    bars: 46, file: 'Music/Spin.ogg',
    cover: 'Music/Spin/Spin.png',
    stemDir: 'Music/Spin/',
    stemPrefix: 'Spin',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4, 5],
    endCutoff: 138.7,
    pattern: [1,0,0,1,0,1,0,0, 1,0,0,1,0,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
    // ★ 드럼 strict (1.2) 으로 sparse 해짐 (사용자 보고 2026-05-04). 신스 강화 버전 (9ee3e68) 으로 revert.
    stemSensitivity: { 0: 1.05, 6: 1.05 }, // drum + 신스 둘 다 lenient
    slotSubdivision: 0.5, // 모든 난이도 슬롯 절반 (지옥 32분 = 96ms@78BPM)
    slotStemPriority: [3, 6, 0, 1, 2], // 신스 > other > drum > bass > vocal
    levelBonus: 0.3, // 실제 노트 밀도 반영해 표시 레벨 ↑
  },
  {
    name: 'Starlight', sub: 'DREAM POP', bpm: 129,
    color: '#8e7bff', bg1: '#0c081e', bg2: '#16102b',
    bars: 72, file: 'Music/Starlight.ogg',
    cover: 'Music/Starlight/Starlight.png',
    stemDir: 'Music/Starlight/',
    stemPrefix: 'Starlight',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 131.2,
    pattern: [1,0,1,0,1,0,1,0, 0,1,0,1,1,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'Sugar Pixel', sub: 'J-POP', bpm: 152,
    color: '#ff6ec7', bg1: '#1f0814', bg2: '#2d0e1f',
    bars: 92, file: 'Music/Sugar_Pixel.ogg',
    cover: 'Music/Sugar_Pixel/Sugar_Pixel.png',
    stemDir: 'Music/Sugar_Pixel/',
    stemPrefix: 'Sugar_Pixel',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4, 5],
    endCutoff: 143.2,
    pattern: [1,0,1,1,0,1,0,1, 1,0,0,1,1,0,1,0],
    chordMode: true,
  },
  {
    name: '우리뿐인 밤', sub: 'K-EMOTION', bpm: 161,
    color: '#f59ec2', bg1: '#150815', bg2: '#220c20',
    bars: 64, file: 'Music/우리뿐인_밤.ogg',
    cover: 'Music/우리뿐인_밤/우리뿐인_밤.png',
    stemDir: 'Music/우리뿐인_밤/',
    stemPrefix: '우리뿐인_밤',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    pattern: [1,0,1,0,0,1,0,1, 1,0,1,0,1,0,0,1],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'ATLANTIS', sub: 'OCEAN AMBIENT', bpm: 86,
    color: '#4287f5', bg1: '#050a14', bg2: '#0a1428',
    bars: 57, file: 'Music/ATLANTIS.ogg',
    cover: 'Music/ATLANTIS/ATLANTIS.png',
    stemDir: 'Music/ATLANTIS/',
    stemPrefix: 'ATLANTIS',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [0, 1, 4, 5, 6],
    endCutoff: 155.7,
    stemSensitivity: { 2: 0.9, 3: 0.9 }, // vocals + instrum 매우 lenient (excludeStems 라 source 부족)
    stemMinGap: { 2: 20, 3: 20 },          // 짧은 minGap → onset 더 많이 감지
    slotSubdivision: 0.5,                  // 모든 난이도 dense (default 의 절반)
    levelBonus: 0.4,                       // dense 옵션으로 실제 밀도 ↑ → 표시 레벨 +4~5
    pattern: [1,0,0,1, 0,0,1,0, 1,0,0,1, 0,1,0,0],
    chordMode: true,
  },
  {
    name: 'Right Now', sub: 'DANCE POP', bpm: 144,
    color: '#ff5577', bg1: '#150510', bg2: '#20081a',
    bars: 73, file: 'Music/Right_Now.ogg',
    cover: 'Music/Right_Now/Right_Now.png',
    stemDir: 'Music/Right_Now/',
    stemPrefix: 'Right_Now',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4, 5],
    endCutoff: 120.2,
    pattern: [1,0,1,0, 1,0,1,0, 1,0,1,1, 0,1,0,1],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: 'Switch It Up', sub: 'DANCE POP', bpm: 144,
    color: '#00d2ff', bg1: '#050f1a', bg2: '#08182a',
    bars: 78, file: 'Music/Switch_It_Up.ogg',
    cover: 'Music/Switch_It_Up/Switch_It_Up.png',
    stemDir: 'Music/Switch_It_Up/',
    stemPrefix: 'Switch_It_Up',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4],
    pattern: [1,0,1,1, 0,1,0,1, 1,0,1,0, 1,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '달빛 과자상자', sub: 'K-EMOTION', bpm: 129,
    color: '#c4a4ff', bg1: '#100820', bg2: '#1a0e2e',
    bars: 91, file: 'Music/달빛_과자상자.ogg',
    cover: 'Music/달빛_과자상자/달빛_과자상자.png',
    stemDir: 'Music/달빛_과자상자/',
    stemPrefix: '달빛_과자상자',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4],
    endCutoff: 165.7,
    pattern: [1,0,0,1, 1,0,1,0, 0,1,0,1, 1,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '이건 아직 시작이야', sub: 'K-POP', bpm: 136,
    color: '#ff9900', bg1: '#170a05', bg2: '#25140a',
    bars: 100, file: 'Music/이건_아직_시작이야.ogg',
    cover: 'Music/이건_아직_시작이야/이건_아직_시작이야.png',
    stemDir: 'Music/이건_아직_시작이야/',
    stemPrefix: '이건_아직_시작이야',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 173.7,
    pattern: [1,0,1,0, 0,1,0,1, 1,0,1,0, 1,0,1,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '흐릿한 이 밤', sub: 'K-BALLAD', bpm: 123,
    color: '#6b9eff', bg1: '#050d18', bg2: '#0c1828',
    bars: 79, file: 'Music/흐릿한_이_밤.ogg',
    cover: 'Music/흐릿한_이_밤/흐릿한_이_밤.png',
    stemDir: 'Music/흐릿한_이_밤/',
    stemPrefix: '흐릿한_이_밤',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    endCutoff: 144.2,
    pattern: [1,0,0,1, 0,0,1,0, 1,0,0,1, 0,1,0,0],
    vocalIntroRange: 'auto', chordMode: true,
  },
  {
    name: '夢緣 (몽연)', sub: 'AMBIENT BALLAD', bpm: 89,
    color: '#a08cff', bg1: '#0a0820', bg2: '#1a1430',
    bars: 63, file: 'Music/夢緣_(몽연).ogg',
    cover: 'Music/夢緣_(몽연)/夢緣_(몽연).png',
    stemDir: 'Music/夢緣_(몽연)/',
    stemPrefix: '夢緣_(몽연)',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [0, 1, 4, 5, 6],
    endCutoff: 165.7,
    pattern: [1,0,0,1, 0,0,1,0, 1,0,0,1, 0,1,0,0],
    chordMode: true,
    stemSensitivity: { 2: 0.9, 3: 0.9 },
    stemMinGap: { 2: 20, 3: 20 },
    slotSubdivision: 0.5,
    levelBonus: 0.4,
  },
  {
    name: 'Artificial Sky', sub: 'INDIE/POP', bpm: 96, color: '#6a8cff',
    bg1: '#0a0e1a', bg2: '#141a2e', bars: 55,
    cover: 'Music/Artificial_Sky/Artificial_Sky.png',
    file: 'Music/Artificial_Sky.ogg',
    stemDir: 'Music/Artificial_Sky/',
    stemPrefix: 'Artificial_Sky',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4, 5],
    chordMode: true, chordMinGap: 2.5,
    vocalIntroRange: 'auto',
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,1,0,1,0],
  },
  {
    name: 'Red Light', sub: 'ROCK/EDM', bpm: 152, color: '#ff3a5c',
    bg1: '#1a0008', bg2: '#2e0014', bars: 73,
    cover: 'Music/Red_Light/Red_Light.png',
    file: 'Music/Red_Light.ogg',
    stemDir: 'Music/Red_Light/',
    stemPrefix: 'Red_Light',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4, 5],
    chordMode: true, chordMinGap: 2.0,
    vocalIntroRange: 'auto',
    endCutoff: 113.2,
    pattern: [1,1,0,1,0,1,1,0, 1,0,1,1,0,1,0,1],
  },
  {
    name: 'Static On The Road', sub: 'SYNTH/POP', bpm: 129, color: '#4dd0e1',
    bg1: '#001218', bg2: '#00242e', bars: 66,
    cover: 'Music/Static_On_The_Road/Static_On_The_Road.png',
    file: 'Music/Static_On_The_Road.ogg',
    stemDir: 'Music/Static_On_The_Road/',
    stemPrefix: 'Static_On_The_Road',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4, 5],
    chordMode: true, chordMinGap: 2.2,
    vocalIntroRange: 'auto',
    pattern: [1,0,1,1,0,1,0,1, 1,0,0,1,1,0,1,0],
  },
  {
    name: 'Mirrorball Kiss', sub: 'DISCO/FUNK', bpm: 129, color: '#ffd54f',
    bg1: '#1a0f00', bg2: '#2e1c00', bars: 93,
    cover: 'Music/Mirrorball_Kiss/Mirrorball_Kiss.png',
    file: 'Music/Mirrorball_Kiss.ogg',
    stemDir: 'Music/Mirrorball_Kiss/',
    stemPrefix: 'Mirrorball_Kiss',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [5],
    chordMode: true, chordMinGap: 2.2,
    vocalIntroRange: 'auto',
    pattern: [1,0,1,1,0,1,1,0, 1,0,1,1,0,1,0,1],
  },
  // ===== A/B 테스트 임시 엔트리 (MVSEP vs Demucs stem 비교) — 테스트 후 제거 =====
  {
    name: 'Arcade Turnabout [MVSEP]', sub: 'A/B 테스트 · MVSEP', bpm: 129, color: '#4dd0e1',
    bg1: '#001218', bg2: '#00242e', bars: 99,
    cover: 'Music/Arcade_Turnabout.png',
    file: 'Music/Arcade_Turnabout.ogg',
    stemDir: 'Music/Arcade_Turnabout_mvsep/',
    stemPrefix: 'Arcade_Turnabout',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    chordMode: true,
    endCutoff: 178.7,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
  },
  {
    name: 'Arcade Turnabout [Demucs]', sub: 'A/B 테스트 · Demucs', bpm: 129, color: '#4dd0e1',
    bg1: '#001218', bg2: '#00242e', bars: 99,
    cover: 'Music/Arcade_Turnabout.png',
    file: 'Music/Arcade_Turnabout.ogg',
    stemDir: 'Music/Arcade_Turnabout_demucs/',
    stemPrefix: 'Arcade_Turnabout',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    chordMode: true,
    endCutoff: 178.7,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
  },
  {
    name: '봉인해제 Dragon [MVSEP]', sub: 'A/B 테스트 · MVSEP', bpm: 99, color: '#ff6b3a',
    bg1: '#1a0800', bg2: '#2e1200', bars: 71,
    cover: 'Music/봉인해제_Dragon.png',
    file: 'Music/봉인해제_Dragon.ogg',
    stemDir: 'Music/봉인해제_Dragon_mvsep/',
    stemPrefix: '봉인해제_Dragon',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4],
    chordMode: true,
    endCutoff: 169.7,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
  },
  {
    name: '봉인해제 Dragon [Demucs]', sub: 'A/B 테스트 · Demucs', bpm: 99, color: '#ff6b3a',
    bg1: '#1a0800', bg2: '#2e1200', bars: 71,
    cover: 'Music/봉인해제_Dragon.png',
    file: 'Music/봉인해제_Dragon.ogg',
    stemDir: 'Music/봉인해제_Dragon_demucs/',
    stemPrefix: '봉인해제_Dragon',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    excludeStems: [4],
    chordMode: true,
    endCutoff: 169.7,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
  },
  {
    name: '잔상 [MVSEP]', sub: 'A/B 테스트 · MVSEP', bpm: 99, color: '#a08cff',
    bg1: '#0a0820', bg2: '#1a1430', bars: 38,
    cover: 'Music/잔상.png',
    file: 'Music/잔상.ogg',
    stemDir: 'Music/잔상_mvsep/',
    stemPrefix: '잔상',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    chordMode: true,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
  },
  {
    name: '잔상 [Demucs]', sub: 'A/B 테스트 · Demucs', bpm: 99, color: '#a08cff',
    bg1: '#0a0820', bg2: '#1a1430', bars: 38,
    cover: 'Music/잔상.png',
    file: 'Music/잔상.ogg',
    stemDir: 'Music/잔상_demucs/',
    stemPrefix: '잔상',
    stemNames: ['drums', 'bass', 'vocals', 'instrum', 'piano', 'guitar', 'other'],
    chordMode: true,
    pattern: [1,0,1,0,1,1,0,1, 0,1,0,1,0,1,1,0],
  },
];
console.log("songs OK count="+songs.length);
console.log(songs.slice(-6).map(s=>s.name+" | "+s.stemDir).join("
"));